name: Docker Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.dispatch.sh/maartje/itf-steunt-je:$GITHUB_SHA
    - name: Log in to registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.dispatch.sh -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push image
      run: docker push registry.dispatch.sh/maartje/itf-steunt-je:$GITHUB_SHA
